<?php

namespace TestAutomation\All4BomBundle\Repository;

use Behat\Gherkin\Node\ScenarioInterface;
use TestAutomation\All4BomBundle\Entity\ScenarioItem;

/**
 * ScenarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScenarioRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * @param ScenarioInterface $scenario
     */
    public function createScenario($scenario)
    {
        $title = $scenario->getTitle();

        /**@var $newScenario ScenarioItem */
        $newScenario = new ScenarioItem();
        $newScenario->setTitle($title);
        $newScenario = $this->getEntityManager()->merge($newScenario);
        $this->getEntityManager()->flush();

        $tagRep = $this->getEntityManager()->getRepository("TestAutomationAll4BomBundle:Tag");
        $tags = $scenario->getTags();
        $tagRep->createTags($newScenario, $tags);

//        $stepRep = $this->getEntityManager()->getRepository("TestAutomationAll4BomBundle:Step");
//        $steps = $scenario->getSteps();

    }
}
