<?php

namespace TestAutomation\All4BomBundle\Repository;

use Behat\Gherkin\Node\StepNode;
use TestAutomation\All4BomBundle\Entity\Step;

/**
 * StepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepRepository extends \Doctrine\ORM\EntityRepository
{

}
