<?php

namespace TestAutomation\All4BomBundle\Repository;

/**
 * TestRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRangeRepository extends \Doctrine\ORM\EntityRepository
{
    const STATUS_NOT_RUN = "NOT RUN";
    const STATUS_RUN = "RUN";
    const STATUS_FAIL = "FAIL";
    const STATUS_PASS = "PASS";
}
